version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - AUTH_PORT=8000
      - AUTH_HOST=0.0.0.0
      - DB_HOST=${DB_HOST}  
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER} 
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped

  tasks-service:
    build: ./tasks-service
    ports:
      - "8001:8001"
    environment:
      - TASKS_PORT=8001
      - TASKS_HOST=0.0.0.0
      - DB_HOST=${DB_HOST}  
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER} 
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx/ssl:/etc/nginx/ssl:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - tasks-service
    restart: unless-stopped